config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    root to: redirect('/home')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  resources :employee_salaries
  resources :low_performance_high_salaries
  resources :high_paid
  resources :high_performance_high_leave
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
	has_many :salaries
	has_many :performances
	has_many :leave_takens
	has_one :salary_detail

	
	def self.get_average_performance
		
		average_performances = []
		EmployeeDetail.all.each do |employee|
			average_performance = {}
			average_performance["employee_id"] = employee.id
			average_performance["points"] = employee.performances.average(:points)
			average_performance["name"] = employee.emp_name
			average_performance["salary"] = SalaryDetail.get_salary(employee.id)
			average_performances << average_performance
		end
		return average_performances
	end

	def self.high_performance_high_leave
		emp_details = []
		average_leave = LeaveTaken.average_leave
		average_salary = Salary.avg_salary
		EmployeeDetail.get_average_performance.each do |value|
			total_leave_taken = LeaveTaken.where(:employee_detail_id => value["employee_id"]).sum(:days)
			
			if value["salary"].to_i > average_salary.to_i and total_leave_taken.to_f > average_leave.to_f
				 temp_obj_array = {}
				 temp_obj_array["ename"] = value["name"]
				 temp_obj_array["salary"] = value["salary"]
				 temp_obj_array["leave_taken"] = total_leave_taken.to_i
				 emp_details << temp_obj_array
			end
		end
		return emp_details
	end

end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave_taken.rb
class LeaveTaken < ApplicationRecord
  belongs_to :employee_detail

  def self.average_leave
  	return (LeaveTaken.sum(:days) / EmployeeDetail.count).to_f
  end
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :employee_detail



  def self.get_low_performer_high_salary(salary=nil)
    
    low_perf = []
    
    if salary.present?
      average_salary = salary
    else
      average_salary = Salary.avg_salary
    end
  	   
  	average_performances = EmployeeDetail.get_average_performance()
  	average_performances.each do |value|
      if value["salary"].present? and value["points"].present?
    		if value["salary"].to_i >= average_salary.to_i && value["points"] < 5
          temp_obj_array = {}
    			temp_obj_array["ename"] = value["name"]
          temp_obj_array["salary"] = value["salary"]
          temp_obj_array["average_salary"] = Salary.avg_salary
          temp_obj_array["performance"] = value["points"]
          low_perf << temp_obj_array
    		end
      end
  	end
    return low_perf

  end
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee_detail

  def self.employee_salary(id=nil,month=nil)
    arr = {}
    array = []
    if Salary.find_by(:employee_detail_id => id).present? and Salary.find_by(:month => month).present?
    	if id.present? and month.present?
    		 arr["salary"] = Salary.find_by(:employee_detail_id => id, :month => month).emp_salary
    	elsif id.present? 
    		 arr["salary"] = Salary.find_by(:employee_detail_id => id).emp_salary
      else
         EmployeeDetail.pluck(:id).each do |id|
            arr = {}
            arr["month"] = Salary.find_by(:employee_detail_id => id).month
            arr["salary"] = Salary.find_by(:employee_detail_id => id).emp_salary
            arr["ename"] = EmployeeDetail.find_by(:id => id).emp_name
            array << arr
         end
         return array
    	end
         arr["ename"] = EmployeeDetail.find_by(:id => id).emp_name
         array << arr
         return array
    end
  end

  def self.avg_salary(limit=nil)
  	average_salary = SalaryDetail.get_average_salary
  	return average_salary
  end

end

app/models/salary_detail.rb
class SalaryDetail < ApplicationRecord
  belongs_to :employee_detail

  def self.get_average_salary
		return SalaryDetail.average(:salary).to_f
	end

  def self.get_salary(id)
  	return SalaryDetail.find_by(:employee_detail_id => id).salary
  end

  def self.high_paid(limit=10)
  	names = []
  	SalaryDetail.order("salary DESC").limit(limit.to_i).each do |salary|
  		temp_array = {}
      temp_array["ename"] = salary.employee_detail.emp_name
      temp_array["salary"] = salary.salary
      names << temp_array
  	end
  	return names.uniq
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employee_salaries_controller.rb
class EmployeeSalariesController < ApplicationController
	def index
		id = params[:id]
		month = params[:month]
		if id and month
			@salaries = Salary.employee_salary(id,month)
		else
			@salaries = []
		end

		if @salaries.nil?
			@salaries = []
		end
	end
end

app/controllers/high_paid_controller.rb
class HighPaidController < ApplicationController
	def index
		@high_paid_employee = SalaryDetail.high_paid(params[:q])
	end
end

app/controllers/high_performance_high_leave_controller.rb
class HighPerformanceHighLeaveController < ApplicationController
	def index
		@employees = EmployeeDetail.high_performance_high_leave
		if @employees.nil?
			@employees = []
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	
		# @low_performance_highly_paid = Performance.get_low_performer_high_salary
		# @high_performers_high_leave = EmployeeDetail.high_performance_high_leave
	end

end

app/controllers/low_performance_high_salaries_controller.rb
class LowPerformanceHighSalariesController < ApplicationController
	def index
		@employees = Performance.get_low_performer_high_salary(params[:salary])
		@employees.each do |e|
			@average = e["average_salary"]
			@performance = e["performance"]
		end
		if @employees.nil?
			@employees = []
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_salaries_helper.rb
module EmployeeSalariesHelper
end

app/helpers/high_paid_helper.rb
module HighPaidHelper
end

app/helpers/high_performance_high_leave_helper.rb
module HighPerformanceHighLeaveHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/low_performance_high_salaries_helper.rb
module LowPerformanceHighSalariesHelper
end

app/views/employee_salaries/index.html.erb
<div class="container">
	<div id="title">
		<center>
			<b><header>HR Management System</header></b>
		</center>
	</div>

	<div id="back">
		<%= link_to "Back", home_index_path(), class: 'back_button' %>
	</div>

	<div>
		<div id="content">
			<center>
				<%= form_tag("/employee_salaries", method: "get") do %>
				<div>	  
				  <%= text_field_tag(:id, "", class: 'input form-control', :placeholder => "Enter employee Id") %>
				  
				  <%= select_tag("month", options_for_select([["January","Jan"],["February","Feb"],["March","Mar"],["April","Apr"],["May","May"],["June","Jun"],["July","Jul"],["August","Aug"],["September","Sep"],["October","Oct"],["November","Nov"],["December","Dec"]],params[:per_page].to_s),{:name => "month" , class: "month"} ) %>
				</div>
				<div>
		  			<%= submit_tag("Get", class: 'get_button')  %>
				</div>
				<% end %>
			</center>
		</div>

		<% if @salaries.count>0 %>
		<center>
			<div id="result">
				<table class="table table-bordered">
				  <tr>
				  	<th>Id</th>
				    <th>Name</th>
				    <th>Salary</th>
				  </tr>
				  <% @salaries.each_with_index do |employee,index| %>
				  <tr>
				  	<td><%= index+1 %></td>
				    <td><%= employee["ename"] %></td>
				    <td><%= employee["salary"] %></td>
				  </tr>
				 <% end %>
				</table>
			</div>
		</center>
		<% end %>
	</div>
</div>

app/views/high_paid/index.html.erb
<div class="container">
  <div id="title">
    <center>
      <b><header>HR Management System</header></b>
    </center>
  </div>

  <div id="back">
    <%= link_to "Back", home_index_path(), class: 'back_button' %>
  </div>


  <div>
    <div id="content">
      <center>
        <div>
        <%= form_tag("/high_paid", method: "get") do %>
        <%= text_field_tag(:q, "", class: "input form-control", :placeholder => "Enter Limit")  %>
       </div>
        <%= submit_tag("Search", class: "get_button" ) %>
        <% end %>
      </center>
    </div>

    <% if @high_paid_employee.count > 0 %>
    <center>
      <div id="result">
        <table class="table table-bordered">
              <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Salary</th>
              </tr>

               <% @high_paid_employee.each_with_index do |employee,index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= employee["ename"] %></td>
                <td><%= employee["salary"] %></td>
              </tr>
              <% end %>
          </table>
        </div>
      </center>
      <% end %>
  </div>
</div>

app/views/high_performance_high_leave/index.html.erb
<div class="container">
	<div id="title">
	  <center>
	    <b><header>HR Management System</header></b>
	  </center>
	</div>
	<br>
	<div>
		<center><h4>High performers with low attendance.</h4></center>
	</div>

	<div id="back">
	  <%= link_to "Back", home_index_path(), class: 'back_button' %>
	</div>

	<% if @employees.count > 0 %>
	<center>
		<div id="result">
			<table class="table table-bordered">
			<tr>
			  <th>Id</th>
			  <th>Name</th>
			  <th>Salary</th>
			  <th>Leave Taken (No of days)</th>
			</tr>
	        <% @employees.each_with_index do |employee,index| %>
		    <tr>
		      <td><%= index+1 %></td>
		      <td><%= employee["ename"] %></td>
			  <td><%= employee["salary"] %></td>
			  <td><%= employee["leave_taken"] %></td>
			</tr>
			<% end %>
			</table>
		</div>
	</center>
	<% end %>
</div>

app/views/home/index.html.erb
<div class="container">
	<div id="title">
		<center>
			<b><header>HR Management System</header></b>
		</center>
	</div>

	<center>
		<div id="links">
			<%= link_to "Employee Salary", employee_salaries_path(), class: "button" %>
			<%= link_to "High Paid", high_paid_index_path(), class: "button" %>
			<%= link_to "Low Performers", low_performance_high_salaries_path(), class: "button" %>
			<%= link_to "High Performers", high_performance_high_leave_index_path(), class: "button" %>
			<%=  link_to "Admin", rails_admin_path(),  class: "button" %> 
		</div>
	</center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HRSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/low_performance_high_salaries/index.html.erb
<div class="container">
	<div id="title">
	  <center>
	    <b><header>HR Management System</header></b>
	  </center>
	</div>
	<br>
	<div>
		<center><h4>Low performers with high salary.</h4></center>
	</div>
	<div id="back">
	  <%= link_to "Back", home_index_path(), class: 'back_button' %>
	</div>

	<div id="content">
		<center>
		<%= form_tag("/low_performance_high_salaries", method: "get") do %>
			<div>
			  <%= text_field_tag(:salary, "", class: "input form-control", :placeholder => "Enter minimum salary") %>
			</div>
			<div>
			  <%= submit_tag("Get", class: 'get_button') %>
			</div>
			<% end %>
		</center>
	</div>
	
	<div id="stats">
		<div class="row">
			<div class="col-md-6">
				<h4> <b>Average Salary :</b> <%= @average %></h4>
			</div>
			<div class="col-md-6">
				<h4> <b>Average Performance :</b> 5.0 /10</h4>
			</div>
		</div>
	</div>

	<% if @employees.count > 0 %>
	<center>
		<div id="result">
			<table class="table table-bordered">
			  <tr>
			  	<th>Id</th>
			    <th>Name</th>
			    <th>Salary</th>
			    <th>Performance</th>
			  </tr>

			  <% @employees.each_with_index do |employee,index| %>
			  <tr>
			  	<td><%= index+1 %></td>
			    <td><%= employee["ename"] %></td>
			    <td><%= employee["salary"] %></td>
			    <td><%= employee["performance"] %></td>
			  </tr>
			 <% end %>
			</table>
		</div>
	</center>
	<% end %>
</div>